name: Test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Set platform info
        if: ${{ matrix.os == 'windows-latest' }}
        run: cd vendor && curl -R -O http://www.lua.org/ftp/lua-5.4.3.tar.gz && tar zxf lua-5.4.3.tar.gz && cd lua-5.4.3 && make MYCFLAGS=-fPIC PLAT=mingw all -j4
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test
